### ISSUE TITLE
Preview Widget not masking texture to alpha of source texture

### ISSUE THREAD

**Issue by Jefficus** [kivy-garden/drag_n_drop#2]
When I draw a draggable widget that has transparent regions, the default preview widget still fills its texture with a semi-transparent black layer rather than masking to the alpha of the source widget. This means that rounded buttons suddenly become sharp rectangles when dragging them.

**To Reproduce**
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.stacklayout import StackLayout
from kivy.uix.gridlayout import GridLayout
from kivy_garden.drag_n_drop import DraggableObjectBehavior
from kivy_garden.drag_n_drop import DraggableLayoutBehavior

class DraggableGridLayout(DraggableLayoutBehavior, GridLayout):
    def compare_pos_to_widget(self, widget, pos):
        if pos[1] < widget.y:
            return 'after'
        elif pos[1] >= widget.y + widget.size[1]:
            return 'before'
        elif pos[0] >= widget.center_x:
            return 'after'
        else:
            return 'before'

    def handle_drag_release(self, index, drag_widget):
        self.add_widget(drag_widget, index)


class DraggableBoxLayout(DraggableLayoutBehavior, BoxLayout):
    def compare_pos_to_widget(self, widget, pos):
        if self.orientation == 'lr-tb':
            return 'before' if pos[1] >= widget.center_y else 'after'
        return 'before' if pos[0] < widget.center_x else 'after'

    def handle_drag_release(self, index, drag_widget):
        self.add_widget(drag_widget, index)


class DragLabel(DraggableObjectBehavior, Label):

    def initiate_drag(self):
        # during a drag, we remove the widget from the original location
        self.parent.remove_widget(self)


# You could also put the following in your kv file...
kv = '''
<AlphaLabel@DragLabel>:
    canvas.before:
        Color:
            rgba: 0.6,0.0,0.4,1
        Rectangle:
            pos: self.pos[0] + self.size[0]/3, self.pos[1]
            size: self.size[0]/3, self.size[1]

BoxLayout:
    orientation: 'vertical'
    DraggableGridLayout:
        drag_classes: ['label']
        size_hint: 1,1
        rows: 3
        cols: 3
        canvas.before:
            Color:
                rgba: 0.6,0.6,0.6,1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: 'Label 1'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 0.6,1,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 2'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 1,1,0.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 3'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 1,0.6,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 3'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 0.6,0.6,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 3'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 1,0.6,0.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 3'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 1,0.6,0.3,1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            text: 'Label 3'
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 0.3,0.6,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size


    DraggableBoxLayout:
        drag_classes: ['label']
        orientation: 'horizontal'
        canvas.before:
            Color:
                rgba: 0.4,0.4,0.4,1
            Rectangle:
                pos: self.pos
                size: self.size
        AlphaLabel:
            text: 'Drag Me'
            color: 0,0,0,1
            background_color: 1,0,1,1
            size_hint: 0.33,0.16
            background_normal:''
            drag_cls: 'label'
        AlphaLabel:
            text: 'Or Me'
            background_color: 1,1,0,1
            background_normal:''
            size_hint: 0.33,0.16
            drag_cls: 'label'
            color: 0,0,0,1
'''

class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

TestApp().run()
```

**Expected behavior**
Running the example shows that the draggable widgets have transparent flanks, but those flanks are filled with semitransparent gray during drag. I would expect the preview shape to have the same alpha contour as the source item.

**Additional context**
It's entirely possible that this is already handled and I'm just not seeing the mechanism that turns it on. Apologies if this is the case. I've read through the implementation code, but I'm not familiar enough with the Fbo and Canvas manipulations to see the trick of how to do this.
